nzandi0/sake-project

app/controllers/nihonshus_controller.rb, app/views/nihonshus/index.html.erb, app/views/nihonshus/search.html.erb, config/routes.rb, db/schema.rb, db/seeds.rb
Added new Nihonshu Controller
Added new view(search,index)
changed routes(root:)
=> Controller nihonshu

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
changed navbar background color to white and fixed position as well as prevented overlap of background
=> Navbar fixed

app/assets/javascripts/scanner.js, app/controllers/nihonshus_controller.rb, config/application.rb, config/routes.rb, db/seeds.rb
Reverts nzandi0/sake-project#20
=> Revert "Camera backend"

app/controllers/nihonshus_controller.rb, app/controllers/reviews_controller.rb, app/controllers/users_controller.rb, app/models/review.rb, app/views/nihonshus/show.html.erb, app/views/reviews/_form.html.erb, app/views/reviews/_show.html.erb, app/views/reviews/create.html.erb, app/views/reviews/create.js.erb, app/views/users/show.html.erb, config/routes.rb
review function with AJAX implemented in the show page of product
=> Review ajax

app/controllers/savings_controller.rb, app/models/saving.rb, db/schema.rb
validation for save action so that you cannot save the same item more than once.
=> Save validation

app/data/data.json, app/models/nihonshu.rb, app/views/nihonshus/search.html.erb, app/views/nihonshus/search_attr.html.erb, app/views/nihonshus/show.html.erb, db/migrate/20171031023324_change_acidity_data_type_in_nihonshu_table.rb, db/migrate/20171031023944_change_body_data_type_in_nihonshu_table.rb, db/migrate/20171031043519_add_image_url_to_nihonshus_table.rb, db/schema.rb, db/seeds.rb
changed seed file and show&search page
=> fixed search by attribute

app/data/data.json, app/models/nihonshu.rb, app/views/nihonshus/index.html.erb, db/schema.rb, db/seeds.rb
changed seed, added selection part by price and popular three sake.
=> Selection part

app/assets/stylesheets/pages/_search.scss, app/views/nihonshus/search.html.erb
Reverts nzandi0/sake-project#53
=> Revert "Homepage"

app/views/nihonshus/search.html.erb, db/schema.rb
error fixed with compare function
=> fixed search error

app/data/data.json
=> New sake seed

db/seeds.rb
=> Review seed

app/views/nihonshus/index.html.erb
=> fixed index page sake name,price

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_modal.scss, app/assets/stylesheets/pages/_home.scss, app/views/comparisons/display.html.erb, app/views/layouts/application.html.erb, app/views/nihonshus/index.html.erb, app/views/nihonshus/show.html.erb, app/views/shared/_modal.html.erb
modal complete with some front end bug fixes. note that javascript files allocated to application.html.erb and _modal.html.erb
=> Modal search

app/views/nihonshus/index.html.erb, db/seeds.rb
added selection by taste (dry) for user journey.
changed seed ( used real name in email address , and added reviews)
=> Selection taste

app/assets/stylesheets/components/_modal.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/nihonshus_controller.rb, app/controllers/savings_controller.rb, app/views/nihonshus/show.html.erb
modal styling complete and average rating complete.
=> Average rating

app/assets/stylesheets/components/_navbar.scss
=> padding on navbar fixed

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/views/devise/sessions/new.html.erb
=> Login desgin

app/controllers/reviews_controller.rb, app/models/review.rb, app/views/reviews/_form.html.erb
delete title from Model,Controller,View
=> Title review

app/assets/javascripts/scanner.js, app/assets/stylesheets/components/_scanner.scss, app/views/nihonshus/index.html.erb
=> Camera modal

app/views/comparisons/display.html.erb
=> graph label changed from taste to dryness

app/assets/stylesheets/components/_alert.scss, app/assets/stylesheets/components/_navbar.scss
the alert message will now be displayed below the navbar not behind it!
=> fixed alert message behind navbar bug

app/views/devise/registrations/new.html.erb
quick design fix for the sign up page
=> sign up page quick design fix

app/views/comparisons/display.html.erb
images on display page now a link
=> Image link

app/views/comparisons/display.html.erb
=> image bug fixed
